### PR TITLE
Image interpolation

### PR DESCRIPTION
**Pull request by tacaswell**
WIP trying to fix the outstanding test failures.

first two commits are solid, the rest are speculative.

### CODE REVIEW

**Comment by tacaswell** [comment]
Trying to bisect when this went wrong lead me to conclude it _never_ worked.  Checking out 
747a780cb793c53efc28e4b3164d1981cf9b9421 and running

```
22:28 $ git describe
v1.3.1rc2-1179-g747a780
```

```python
import matplotlib.pyplot as plt
import six

import numpy as np

from matplotlib.testing.decorators import image_comparison, knownfailureif, cleanup
from matplotlib.image import BboxImage, imread, NonUniformImage
from matplotlib.transforms import Bbox, Affine2D
from matplotlib import rcParams, rc_context
from matplotlib import patches
import matplotlib.pyplot as plt
from matplotlib import mlab
from nose.tools import assert_raises
from numpy.testing import (
    assert_array_equal, assert_array_almost_equal, assert_allclose)

import io
import os


fig = plt.figure()
axes = fig.add_subplot(111)
axes.plot([1, 2, 3])

im_buffer = io.BytesIO()
fig.savefig(im_buffer)
im_buffer.seek(0)
image = imread(im_buffer)

#bbox_im = BboxImage(Bbox([[0, 0], [100, 100]]))
bbox_im = BboxImage(Bbox([[100, 100], [0, 0]]))
bbox_im.set_data(image)

axes.add_artist(bbox_im)


plt.show()
```

(which is the code of the test pulled out into a script)

gives

so

which does not show the bounding box image like it should.  

adding `bbox_im.set_clip_on(False)`  gives

so

which is closer.  

Turning the test tolerance down to 0 both of these tests fail and give the following output:

[bbox_image_inverted.pdf](https://github.com/mdboom/matplotlib/files/76864/bbox_image_inverted.pdf)
bbox_image_inverted


@solvents Do you remember how you generate these test image?

**Comment by tacaswell** [comment]
We should probably re-work this test as the transform it is using is in pixel-space so that changing the figure size and DPI will change the result.

**Comment by mdboom** [comment]
Thanks.  FWIW, I think the bbox inverted test started failing only in the last couple of commits on my image interpolation branch (things that were in response to some PR comments).  But I agree, it's a weird test and should just be changed as you've done here.

**Comment by solvents** [comment]
iirc I filled in the test case with my console log from generating the test images. I can't reproduce the image here either though, and I have the original branch so I suspect it relied on some unspecified backend feature. I had intended to make it a cleanup test but didn't know how, but I should point out that there were no image comparison tests for BboxImage at the time (not sure if there are any now).

**Comment by tacaswell** [comment]
Yes, why the BboxImage is not showing up in pdf _is_ a problem that needs to be fixed.

I am not 100% that my change do RenderPdf is the right way to do this.

**Pull request merged**
