### PR TITLE
Change `savefig.dpi` and `figure.dpi` defaults

### PR DESCRIPTION
**Pull request by three-comrades**
Closes #305.

### CODE REVIEW

**Comment by mdboom** [comment]
Can you submit this against matplotlib master?

**Comment by three-comrades** [comment]
Sure. Will do so later.

**Comment by three-comrades** [comment]
Okay, silly question: do you want me to submit it here against mdboom/matplotlib:master or file a new PR against master upstream?

**Comment by mdboom** [comment]
A new PR against master upstream.

Thanks

**Pull request closed without merging**
